
# Author    KMS - Martin Dubois, P. Eng.
# Copyright (C) 2021 KMS
# License   http://www.apache.org/licenses/LICENSE-2.0
# Product   Maze
# File      Maze_Lib_Test/GenTestList.ps1

Write-Output "Executing  Maze_Lib_Test/GenTestList.ps1  ..."

# ===== Initialisation ======================================================

$TestList = "TestList.h"

# ===== Function ============================================================

function GenDecl
{
    param($Name)

    Add-Content -Path $TestList -Value ( "extern int " + $Name.Substring(0, 8) + "();" )
}

function GenInfo
{
    param($Name)

    Add-Content -Path $TestList -Value ( "    { `"" + $Name + "`", " + $Name.SubString(0, 8) + " }," )
}

# ===== Execution ===========================================================

$Tests = Get-ChildItem -Filter TestA_*.cpp
if ((!$?) -Or (0 -ge $Tests.Length))
{
    Write-Error "ERROR  No test"
    exit 10
}

Clear-Content -ErrorActio SilentlyContinue -Path $TestList

Add-Content -Path $TestList -Value ""
Add-Content -Path $TestList -Value "// Generated by Maze_Lib_Test/GenTestList.ps1"
Add-Content -Path $TestList -Value ""
Add-Content -Path $TestList -Value "typedef struct"
Add-Content -Path $TestList -Value "{"
Add-Content -Path $TestList -Value "    const char * mName;"
Add-Content -Path $TestList -Value "    int (*mFunction)();"
Add-Content -Path $TestList -Value "}"
Add-Content -Path $TestList -Value "TestInfo;"
Add-Content -Path $TestList -Value ""

$Tests | ForEach-Object { GenDecl -Name $_.Name }

Add-Content -Path $TestList -Value ""
Add-Content -Path $TestList -Value "static const TestInfo TESTS[] ="
Add-Content -Path $TestList -Value "{"

$Tests | ForEach-Object { GenInfo -Name $_.Name }

Add-Content -Path $TestList -Value "};"
Add-Content -Path $TestList -Value ""

# ===== End =================================================================

Write-Output OK
